tasks:
  - init: |
      yarn install

ports:
  - port: 3000
    onOpen: ignore
  - port: 3333
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - github.vscode-pull-request-github
    - dbaeumer.vscode-eslint
    - beardedbear.beardedtheme
    - pkief.material-icon-theme
    - bradlc.vscode-tailwindcss
    - syler.sass-indented
    - svelte.svelte-vscode
    - csstools.postcss
